### ISSUE TITLE
Crash on vault encrypted variables

### ISSUE THREAD

**Issue by madic-creates** [murphypetercl/ansible-mdgen#18]
Hey,

under vars I have some ansible-vault encrypted .md files. If I run ansible-mdgen in this role, it crashes with the following error:

```
Output Directory: ./docs
Traceback (most recent call last):
  File "/home/mne-adm/.local/bin/ansible-mdgen", line 6, in <module>
    md = AnsibleMdgen()
  File "/home/mne-adm/.local/lib/python3.9/site-packages/ansiblemdgen/AnsibleMdgenClient.py", line 24, in __init__
    writer.render()
  File "/home/mne-adm/.local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenter.py", line 44, in render
    variablesWriter.render()
  File "/home/mne-adm/.local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenterVariables.py", line 43, in render
    self.iterateOnFilesAndDirectories(self.vars_dir, self.config.get_output_variables_dir())
  File "/home/mne-adm/.local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenterBase.py", line 27, in iterateOnFilesAndDirectories
    self.createMDFile(dirpath, filename, output_directory)
  File "/home/mne-adm/.local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenterVariables.py", line 60, in createMDFile
    self.addVariables(dirpath+"/"+filename, mdFile)
  File "/home/mne-adm/.local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenterVariables.py", line 84, in addVariables
    mdFile.new_paragraph(yaml.safe_dump(variables[variable],  default_flow_style=False))
TypeError: string indices must be integers
```

Vault files begin with $ANSIBLE_VAULT;1.1;AES256. Maybe check for the string and ignore them?

**Comment by murphypetercl** [comment]
Hi Madic, thanks for logging this. I put in a change about 4 days ago (version 0.0.13) which basically ignores any existing .md files as it iterates through the directories. See AutoDocumenterBase.py. Can you confirm the version that you are on? Can you upgrade to the latest and retry as I'm unable to reproduce it.

I did find an issue with vault encrypted variables though so will address that issue.

**Comment by madic-creates** [comment]
I've updated to 0.0.16 and now I get the following error:

```
Do you want to clear the directory and rebuild all the docs? [Y/n] Y
Traceback (most recent call last):
  File "/home/mne-adm/.local/bin/ansible-mdgen", line 6, in <module>
    md = AnsibleMdgen()
  File "/home/mne-adm/.local/lib/python3.9/site-packages/ansiblemdgen/AnsibleMdgenClient.py", line 24, in __init__
    writer.render()
  File "/home/mne-adm/.local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenter.py", line 44, in render
    variablesWriter.render()
  File "/home/mne-adm/.local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenterVariables.py", line 43, in render
    self.iterateOnFilesAndDirectories(self.vars_dir, self.config.get_output_variables_dir())
  File "/home/mne-adm/.local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenterBase.py", line 27, in iterateOnFilesAndDirectories
    self.createMDFile(dirpath, filename, output_directory)
  File "/home/mne-adm/.local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenterVariables.py", line 60, in createMDFile
    self.addVariables(dirpath+"/"+filename, mdFile)
  File "/home/mne-adm/.local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenterVariables.py", line 86, in addVariables
    mdFile.new_paragraph(yaml.safe_dump(variables[variable],  default_flow_style=False).replace('____vault','!vault'))
TypeError: string indices must be integers
```

**Comment by murphypetercl** [comment]
Hey, can you run in debug mode:

ansible-mdgen <path_to_role> -vvv

This should identify on which file it is falling over on.

**Comment by madic-creates** [comment]
It's failing at a vault encrypted file in the vars folder of the role. There are multiple vault encrypted files. It's failing at the first.

**Comment by murphypetercl** [comment]
What is the name of the file? Does it end with .md or something else?

**Comment by murphypetercl** [comment]
the current code ignores .md files but if it's something else then that may be the issue.

**Comment by madic-creates** [comment]
The file has the ending .yml

**Comment by madic-creates** [comment]
Why it's ignoring .md instead of .yml? I'm at least not aware that ansible accesses .md files

**Comment by murphypetercl** [comment]
No ansible doesn't access .md files but I have seen roles where developers place .md files in various directories like vars or defaults (to keep the docs close to the code), hence why I have code in there to ignore .md files (unrelated to vault encrypted files). But I understand your issue more now. In your initial comment you mentioned "ansible-vault encrypted .md" files but I understand now that your .yml files are also encrypted. So as you suggest I will put in a fix to ignore any file that begins with $ANSIBLE_VAULT;1.1;AES256.

Thanks for catching this. Will try and get this fix in later today.

**Comment by madic-creates** [comment]
I'm sorry. My mistake :see_no_evil:

**Comment by murphypetercl** [comment]
No probs at all. I just committed the change there now to ignore any vault encrypted files. Please upgrade and give it a go, thanks.

**Comment by madic-creates** [comment]
It's working! Thank you for your help
