### ISSUE TITLE
error running the generator

### ISSUE THREAD

**Issue by mihai-satmarean** [murphypetercl/ansible-mdgen#22]
although there is some resulted output,
when running the generator from outside the role we get this:
`Output Directory: ./docs
There are existing files in the output directory /Users/role/docs
Do you want to clear the directory and rebuild all the docs? [Y/n] y
Traceback (most recent call last):
  File "/usr/local/bin/ansible-mdgen", line 6, in <module>
    md = AnsibleMdgen()
  File "/usr/local/lib/python3.9/site-packages/ansiblemdgen/AnsibleMdgenClient.py", line 24, in __init__
    writer.render()
  File "/usr/local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenter.py", line 48, in render
    filesTemplatesWriter.render()
  File "/usr/local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenterFilesTemplates.py", line 35, in render
    self.iterateOnFilesAndDirectories(self.files_dir, self.config.get_output_files_dir())
  File "/usr/local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenterBase.py", line 27, in iterateOnFilesAndDirectories
    self.createMDFile(dirpath, filename, output_directory)
  File "/usr/local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenterFilesTemplates.py", line 60, in createMDFile
    self.addFileOrTemplate(dirpath+"/"+filename, mdFile)
  File "/usr/local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenterFilesTemplates.py", line 72, in addFileOrTemplate
    mdFile.new_paragraph(stream.read())
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte`

**Comment by murphypetercl** [comment]
Hi, looks like it's having a problem outputting one of your files under the files or templates directory. Can you run in debug mode (-vvv) and see if you can identify which file it is falling over at? And see if there is something different about the file, thanks.

**Comment by murphypetercl** [comment]
Hi, is this still an issue? If so can you provide some more details - sample file so I can reproduce? If not, I will go ahead and close the issue.

**Comment by mihai-satmarean** [comment]
hi. sorry, actually I tested it now, and maybe due to some other packages updates now works. 
I will reopen if necessary - thanks! a lot

**Comment by murphypetercl** [comment]
Cool thanks
