### ISSUE TITLE
"string indices must be integers" when adding dependency to meta

### ISSUE THREAD

**Issue by madic-creates** [murphypetercl/ansible-mdgen#23]
When adding a dependency ansibe-mdgen crashes. Without dependency, e.g. just [], it's working

meta/main.yml
```
---
galaxy_info:
  author: Peter Murphy
  description: Role to install and configure Minio in distributed mode
  company: My Company
  license: None
  min_ansible_version: 2.9
  platforms:
    - name: RedHat
      versions:
        - 7.8

  galaxy_tags: []

dependencies:
  - geerlingguy.java
```
ansible-mdgen
```
Traceback (most recent call last):
  File "/home/mne-adm/.local/bin/ansible-mdgen", line 6, in <module>
    md = AnsibleMdgen()
  File "/home/mne-adm/.local/lib/python3.9/site-packages/ansiblemdgen/AnsibleMdgenClient.py", line 24, in __init__
    writer.render()
  File "/home/mne-adm/.local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenter.py", line 38, in render
    indexWriter.render()
  File "/home/mne-adm/.local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenterIndex.py", line 20, in render
    self.createIndexMDFile()
  File "/home/mne-adm/.local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenterIndex.py", line 31, in createIndexMDFile
    self.createMDFileContent(mdFile)
  File "/home/mne-adm/.local/lib/python3.9/site-packages/ansiblemdgen/AutoDocumenterIndex.py", line 84, in createMDFileContent
    mdFile.new_line("> "+dep_part+": "+dependency[dep_part])
TypeError: string indices must be integers
```

**Comment by murphypetercl** [comment]
Hi Madic - I have put in a fix for this issue. Please download the latest version and retry, thanks.

**Comment by madic-creates** [comment]
Thank you!
