### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by yyarmoshyk** [murphypetercl/ansible-mdgen#33]
Hello,

I'm getting the following error while running the tool:
```bash
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

The full trace is the following:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/ansible-mdgen", line 6, in <module>
    md = AnsibleMdgen()
         ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ansiblemdgen/AnsibleMdgenClient.py", line 24, in __init__
    writer.render()
  File "/usr/local/lib/python3.11/site-packages/ansiblemdgen/AutoDocumenter.py", line 48, in render
    filesTemplatesWriter.render()
  File "/usr/local/lib/python3.11/site-packages/ansiblemdgen/AutoDocumenterFilesTemplates.py", line 35, in render
    self.iterateOnFilesAndDirectories(self.files_dir, self.config.get_output_files_dir())
  File "/usr/local/lib/python3.11/site-packages/ansiblemdgen/AutoDocumenterBase.py", line 32, in iterateOnFilesAndDirectories
    if not filename.endswith('.md') and self.isFileVaultEncrypted(dirpath, filename) is False:
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ansiblemdgen/AutoDocumenterBase.py", line 41, in isFileVaultEncrypted
    data = stream.readlines()
           ^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

The tool is failing on `gz` and `tar` files (located in `rolename/files` subfolder  trying to read them as plaintext)

**Comment by murphypetercl** [comment]
Code merged.

ansible-mdgen 0.1.1 available
